### ISSUE TITLE
Dataset source?

### ISSUE THREAD

**Issue by FlyToYourMooN** [atosystem/SpeechCLIP#1]
Outstanding job! I just can't seem to find the link to the dataset in the cited paper

**Comment by atosystem** [comment]
Sorry, I forget to include the data preparing script. I will update the repo these days.

**Comment by atosystem** [comment]
@Biqigubafan  Sorry, I forget to include the data preparing script. I will update the repo these days.

**Comment by atosystem** [comment]
@FlyToYourMooN I have updated the repo with data preparation instructions.
I will close this issue now. Feel free to open it again if there is still something wrong.
Thanks~
