### ISSUE TITLE
ImportError: cannot import name 'LightningLoggerBase' from 'pytorch_lightning.loggers'

### ISSUE THREAD

**Issue by seongq** [atosystem/SpeechCLIP#3]
I cloned your codes and installed pytorch_lightning.
When I run your code "example.py", I meet a error message "ImportError: cannot import name 'LightningLoggerBase' from 'pytorch_lightning.loggers'"

Can you let me know how can I fix it?

**Comment by atosystem** [comment]
Hi @seongq 
Is your pytorch_lightning using the same version as mentioned in the `requirement.txt`?

**Comment by seongq** [comment]
Oh, I again cloned.
I installed each package required step by step, following requirement.txt
Finally, I can extract embeddings from audio files.
Thank you!

**Comment by atosystem** [comment]
Nice!
I will close this issue.
